=== Pathoschild/StardewModDataset/dataset/data/json-schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Mod page metadata",
	"description": "The metadata for a Stardew Valley mod page fetched from CurseForge, ModDrop, or Nexus Mods.",
	"type": "object",
	"properties": {
		"Site": {
			"description": "The mod site which has the mod.",
			"type": "string",
			"enum": [ "CurseForge", "ModDrop", "Nexus" ]
		},
		"Id": {
			"description": "The mod page ID within the mod site.",
			"type": "integer"
		},
		"Name": {
			"description": "The mod name based on the mod page.",
			"type": [ "string", "null" ]
		},
		"Author": {
			"description": "The author's canonical name based on the mod page (usually the username). This is identical for all mods uploaded to the same site by a user.",
			"type": [ "string", "null" ]
		},
		"AuthorLabel": {
			"description": "The author's display name based on the mod page, if different from Author. This may differ across mods by the same author, may include free text entered by the uploader on Nexus, or may include multiple names on CurseForge.",
			"type": [ "string", "null" ]
		},
		"TagLine": {
			"description": "A short blurb which describes the mod page, if available.",
			"type": [ "string", "null" ]
		},
		"Description": {
			"description": "The full mod page description body, if available. The format depends on the mod site (e.g. ModDrop uses Markdown and Nexus uses BBCode).",
			"type": [ "string", "null" ]
		},
		"PageUrl": {
			"description": "The full URL to the mod's web page.",
			"type": "string",
			"format": "uri"
		},
		"Version": {
			"description": "The version number based on the mod page, if available. This is the version as shown on the mod page, which may not be a valid semantic version.",
			"type": [ "string", "null" ]
		},
		"Updated": {
			"description": "When the mod metadata last changed, as an ISO 8601 UTC date/time. To the extent supported by each mod site, this covers any change to the mod page (including mod page edits, file uploads, hiding or republishing, etc).",
			"type": "string",
			"format": "date-time"
		},
		"Downloads": {
			"description": "The active downloads on the mod page. The selected files depend on the mod site: CurseForge includes all files; ModDrop includes all files not marked 'old', 'hidden', or 'deleted'; and Nexus includes all files not marked 'old', 'archived', or 'deleted'.",
			"type": "array",
			"items": {
				"$ref": "#/$defs/ModPageDownload"
			}
		},
		"OtherFields": {
			"description": "The remaining fields which weren't mapped to one of the other fields.",
			"type": "object"
		}
	},
	"required": [ "Site", "Id", "Name", "Author", "PageUrl", "Version", "Updated", "Downloads" ],

	"$defs": {
		"ModPageDownload": {
			"description": "A download entry on a mod page.",
			"type": "object",
			"properties": {
				"Id": {
					"description": "The unique ID for this file within the mod site.",
					"type": "integer"
				},
				"Type": {
					"description": "The download type. The meaning depends on the mod site: on CurseForge, 'release' downloads are Main and 'alpha' or 'beta' downloads are Optional; on ModDrop, non-prerelease and non-alternate downloads are Main; on Nexus, files in the 'main' category are Main and those in the 'optional' category are Optional. (For Nexus, all downloads are Optional if the mod page only contains files in non-archived/old/deleted categories that would normally be excluded.)",
					"type": "string",
					"enum": [ "Main", "Optional" ]
				},
				"DisplayName": {
					"description": "The download's title as entered by the uploader.",
					"type": [ "string", "null" ]
				},
				"FileName": {
					"description": "The name of the file when downloaded (usually a .zip file).",
					"type": [ "string", "null" ]
				},
				"Description": {
					"description": "The description text for the file. This may be BBCode on Nexus.",
					"type": [ "string", "null" ]
				},
				"Version": {
					"description": "The version number based on the download info, if any. This is the version as shown on the mod page, which may not be a valid semantic version.",
					"type": [ "string", "null" ]
				},
				"SizeInBytes": {
					"description": "The size of the downloaded file in bytes.",
					"type": "integer",
					"minimum": 0
				},
				"Uploaded": {
					"description": "When the file was uploaded, as an ISO 8601 UTC date/time.",
					"type": "string",
					"format": "date-time"
				},
				"Mods": {
					"description": "The mods detected within this download, based on analysis using the SMAPI toolkit. This is always non-empty, unless the DownloadError or UnpackError fields are set.",
					"type": "array",
					"items": {
						"$ref": "#/$defs/ModFolder"
					}
				},
				"DownloadError": {
					"description": "An error message indicating why the file could not be downloaded, if applicable. This is usually an issue on the mod site (e.g. they quarantined the file).",
					"type": "string"
				},
				"UnpackError": {
					"description": "An error message indicating why the mods could not be unpacked from the downloaded archive, if applicable. This is usually an issue with the file itself (e.g. the author uploaded a corrupted archive).",
					"type": "string"
				},
				"OtherFields": {
					"description": "The remaining fields which weren't mapped to one of the other fields.",
					"type": "object"
				}
			},
			"required": [ "Id", "Type", "DisplayName", "FileName", "Version", "SizeInBytes", "Uploaded", "Mods" ]
		},

		"ModFolder": {
			"description": "A mod folder detected within a download.",
			"type": "object",
			"properties": {
				"Id": {
					"description": "The normalized mod ID from the mod's manifest.json, if found.",
					"type": [ "string", "null" ]
				},
				"DisplayName": {
					"description": "The display name for the mod. This is usually the normalized name from the manifest.json (if it was parseable), else generated based on the folder path in the download.",
					"type": "string"
				},
				"Type": {
					"description": "The detected mod type. One of: ContentPack (contains files loaded as a content pack by another SMAPI mod); Smapi (uses SMAPI directly, e.g. a C# mod); Xnb (a legacy type which replaces game files directly); Ignored (folder is ignored by convention, e.g. because it's prefixed with a dot); or Invalid (mod is invalid and its type could not be determined).",
					"type": "string",
					"enum": [ "ContentPack", "Ignored", "Invalid", "Smapi", "Xnb" ]
				},
				"RelativePath": {
					"description": "The relative path to this mod within the download. Omitted if the mod occupies the entire download.",
					"type": "string"
				},
				"Manifest": {
					"description": "The mod's parsed manifest.json file, if it could be parsed. This is the normalized JSON structure, not the raw text (e.g. JSON comments aren't included).",
					"$ref": "#/$defs/ModManifest"
				},
				"ManifestParseError": {
					"description": "If the mod's manifest.json couldn't be parsed, the error type. One of: EmptyFolder (folder is empty or contains only ignored files); EmptyVortexFolder (folder is an empty folder managed by the Vortex mod manager); IgnoredFolder (folder is ignored by convention); ManifestInvalid (mod's manifest.json could not be parsed); ManifestMissing (folder contains non-ignored and non-XNB files, but none of them are manifest.json); or XnbMod (folder is an XNB mod).",
					"type": "string",
					"enum": [ "EmptyFolder", "EmptyVortexFolder", "IgnoredFolder", "ManifestInvalid", "ManifestMissing", "XnbMod" ]
				},
				"ManifestParseErrorText": {
					"description": "If the mod's manifest.json couldn't be parsed, a human-readable message indicating why (e.g. the message shown in the SMAPI console window).",
					"type": "string"
				}
			},
			"required": [ "Id", "DisplayName", "Type" ]
		},

		"ModManifest": {
			"description": "The parsed manifest.json for a scanned mod.",
			"type": "object",
			"properties": {
				"Name": {
					"description": "The mod name.",
					"type": [ "string", "null" ]
				},
				"Description": {
					"description": "A brief description of the mod.",
					"type": [ "string", "null" ]
				},
				"Author": {
					"description": "The mod author's name.",
					"type": [ "string", "null" ]
				},
				"Version": {
					"description": "The mod version. This is guaranteed to be a semantic version (since an invalid version results in a manifest parse error).",
					"type": "string"
				},
				"MinimumApiVersion": {
					"description": "The minimum SMAPI version required by this mod, if specified. This is guaranteed to be a semantic version.",
					"type": "string"
				},
				"MinimumGameVersion": {
					"description": "The minimum Stardew Valley version required by this mod, if specified. This is guaranteed to be a semantic version.",
					"type": "string"
				},
				"EntryDll": {
					"description": "The name of the DLL to load in the mod directory, if it's a SMAPI (C#) mod.",
					"type": "string"
				},
				"ContentPackFor": {
					"description": "The mod which will read this as a content pack, if it's a content pack.",
					"$ref": "#/$defs/ModManifestContentFor"
				},
				"Dependencies": {
					"description": "The other mods that must be loaded before this mod.",
					"type": "array",
					"items": {
						"$ref": "#/$defs/ModManifestDependency"
					}
				},
				"UpdateKeys": {
					"description": "The namespaced mod IDs to query for updates (like \"Nexus:541\").",
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"UniqueId": {
					"description": "The unique mod ID.",
					"type": "string"
				},
				"OtherFields": {
					"description": "The remaining fields which weren't mapped to one of the other fields.",
					"type": "object"
				}
			},
			"required": [ "Name", "Description", "Author", "Version", "UpdateKeys", "UniqueId" ]
		},

		"ModManifestContentFor": {
			"description": "The mod that will load a content pack, from the content pack's manifest.",
			"type": "object",
			"properties": {
				"UniqueId": {
					"description": "The unique ID of the mod which can read this content pack.",
					"type": [ "string", "null" ]
				},
				"MinimumVersion": {
					"description": "The minimum required version (if any).",
					"type": [ "string", "null" ]
				}
			},
			"required": [ "UniqueId" ]
		},

		"ModManifestDependency": {
			"description": "A mod dependency listed in a mod manifest.",
			"type": "object",
			"properties": {
				"UniqueId": {
					"description": "The unique mod ID to require.",
					"type": [ "string", "null" ]
				},
				"MinimumVersion": {
					"description": "The minimum required version (if any).",
					"type": "string"
				},
				"IsRequired": {
					"description": "Whether the dependency must be installed to use the mod.",
					"type": "boolean"
				}
			},
			"required": [ "UniqueId", "IsRequired" ]
		}
	}
}

=== Pathoschild/StardewModDataset/dataset/data/Nexus/29/29775.json
{
	"Site": "Nexus",
	"Id": 29775,
	"Name": "(CP) Wraith Butterfly Trinket",
	"Author": "xtobefreex",
	"Description": "[u][b]OVERVIEW:[/b][/u]\n<br />This mod is a retexture for the fairy trinket that you unlock and have a chance to find after reaching the weapons mastery.\u00A0\n<br />\n<br />The mod uses the winter glow butterfly sprites that are already in the game, but they are recoloured and with lower transparency to give a more ethereal feel to them.\n<br />\n<br />[center][size=4][b][u]\n<br />VERSION 2.0.0 HAS RELEASED![/u][/b]\n<br />[/size]\uFEFF\n<br />\n<br />I've added a toggle between an altered winter glow butterfly and my own glowing butterfly texture. This can be toggled within the GMCM in game or in the config file that is created after loading the game. The default sprite is the one that I created, but I've kept the original for those who may like it better.\n<br />\n<br />\n<br />\n<br />[img]https://staticdelivery.nexusmods.com/mods/1303/images/29775/29775-1742441867-1893175995.gif[/img]\u00A0[b][u]\n<br />[/u][/b]\n<br />[img]https://staticdelivery.nexusmods.com/mods/1303/images/29775/29775-1742441867-1457678890.gif[/img]\uFEFF\uFEFF\n<br />\n<br />\n<br />[u]An optional file called [b]Wraith Butterfly Trinket Standalone [/b]has been included.[/u] This allows the game to drop a trinket called the Crystal Ring, which will then spawn the wraith butterflies when equipped. The butterflies glow and heal like the fairies do. This mod has a toggle that toggles between the fairies being shown and the wraith butterflies being shown, as the wraith butterflies will replace the fairies. I couldn't figure that one out for the life of me, sorry guys. And please let me know if you run into any issues!\n<br />\n<br />[u][img]https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:bojdpdviokjhfedou2msqhkk/bafkreieycgzwwq7bdplv5mhrspk45qyfbsqs7ekvprlaxzs2fsbwgkrjy4@jpeg[/img][/u]\n<br />[b]\n<br />[u]Only have one version of the Wraith Butterfly Trinket installed at a time! Either download the main file, or the optional file.[/u][/b][/center]\n<br />\n<br />[u][b]Installation:[/b][/u]\n<br />1. Make sure you have the latest versions of\u00A0[url=https://www.nexusmods.com/stardewvalley/mods/2400]SMAPI[/url]\u00A0and\u00A0[url=https://www.nexusmods.com/stardewvalley/mods/1915]Content Patcher[/url]\u00A0installed. [url=https://www.nexusmods.com/stardewvalley/mods/5098]Generic Mod Config Menu[/url] is not required but is recommended.\n<br />2. Unzip the folder into[font=Courier New]\u00A0Stardew Valley/Mods[/font]\n<br />3. Run the game through the SMAPI launcher.\n<br />\n<br />[u][b]Compatibility:[/b][/u]\n<br />[list]\n<br />[*]This mod is intended for Stardew Valley version 1.6 or later versions.\u00A0\n<br />[*]This mod has been tested in single-player and works perfectly fine; multiplayer has not been tested but\u00A0[i]should[/i]\u00A0work. Please make sure all players have the mod to prevent possible errors.\n<br />[*]If you have any mods that retexture the fairy trinket, there will be conflicts. Please only use one fairy trinket retexture mod.\n<br />[/list]",
	"PageUrl": "https://www.nexusmods.com/stardewvalley/mods/29775",
	"Version": "2.0.0",
	"Updated": "2025-04-23T16:35:47+00:00",
	"Downloads": [
		{
			"Id": 127877,
			"Type": "Main",
			"DisplayName": "(CP) Wraith Butterfly Trinket",
			"FileName": "(CP) Wraith Butterfly Trinket-29775-2-0-0-1742440142.zip",
			"Description": "The main version of this mod. Download the optional version instead of this one if you want a Crystal Ring trinket! This one only replaces the fairies with the fairy box trinket.",
			"Version": "2.0.0",
			"SizeInBytes": 4808,
			"Uploaded": "2025-03-20T03:09:02+00:00",
			"Mods": [
				{
					"Id": "xtobefreex.WraithButterflyTrinket",
					"DisplayName": "Wraith Butterfly Trinket",
					"Type": "ContentPack",
					"RelativePath": "[CP] Wraith Butterfly Trinket",
					"Manifest": {
						"Name": "Wraith Butterfly Trinket",
						"Description": "Replaces the fairy trinket's fairy sprite with a glowing butterfly texture.",
						"Author": "xtobefreex",
						"Version": "2.0.0",
						"ContentPackFor": {
							"UniqueId": "Pathoschild.ContentPatcher"
						},
						"Dependencies": [],
						"UpdateKeys": [
							"Nexus: 29775"
						],
						"UniqueId": "xtobefreex.WraithButterflyTrinket"
					}
				}
			],
			"OtherFields": {
				"Uid": 5596342514565,
				"CategoryId": 1,
				"Primary": false
			}
		},
		{
			"Id": 130800,
			"Type": "Optional",
			"DisplayName": "(CP) Wraith Butterfly Trinket Standalone",
			"FileName": "(CP) Wraith Butterfly Trinket Standalone-29775-2-0-0-1745426147.zip",
			"Description": "This is an optional file. It creates a new item called the Crystal Ring that will spawn the Wraith Butterflies and heals and glows like the fairies do. DO NOT have both this and the main mod installed. Only choose one! Still replaces the fairy textures.",
			"Version": "2.0.0",
			"SizeInBytes": 5767,
			"Uploaded": "2025-04-23T16:35:47+00:00",
			"Mods": [
				{
					"Id": "xtobefreex.WBTrinketStandalone",
					"DisplayName": "Wraith Butterfly Trinket -- Standalone",
					"Type": "ContentPack",
					"RelativePath": "[CP] Wraith Butterfly Trinket Standalone",
					"Manifest": {
						"Name": "Wraith Butterfly Trinket -- Standalone",
						"Description": "A standalone trinket that uses a glowing butterfly texture.",
						"Author": "xtobefreex",
						"Version": "2.0.0",
						"ContentPackFor": {
							"UniqueId": "Pathoschild.ContentPatcher"
						},
						"Dependencies": [],
						"UpdateKeys": [
							"Nexus: 29775"
						],
						"UniqueId": "xtobefreex.WBTrinketStandalone"
					}
				}
			],
			"OtherFields": {
				"Uid": 5596342517488,
				"CategoryId": 3,
				"Primary": false
			}
		}
	],
	"OtherFields": {
		"Uid": 5596342416463,
		"UploaderId": 79600733,
		"CategoryId": 25,
		"Adult": false
	}
}

=== Pathoschild/StardewModDataset/dataset/data/Nexus/22/22930.json
{
	"Site": "Nexus",
	"Id": 22930,
	"Name": "Beachside Livestock",
	"Author": "soysauceicecream",
	"Description": "I like the beach farm and wanted animals to match my surroundings. I will upload content patcher versions once I figure that out.\n<br />\n<br />Installation:\n<br />- Download the file\n<br />- navigate to your stardew content folder, commonly within your steamapps folder, open the folder titled 'Animals'\n<br />- Backup your files\n<br />- Drag and drop the xnb files into your Animals folder, replacing existing files\n<br />\n<br />\n<br />The chickens become goldfish\n<br />The cows become manatees\n<br />The sheep become seals\n<br />The goats become seahorses\n<br />The pigs become pink dolphins\n<br />The rabbits become sea bunnies\n<br />The dinosaurs become turtles wearing pirate hats\n<br />The ducks become rubber ducks",
	"PageUrl": "https://www.nexusmods.com/stardewvalley/mods/22930",
	"Version": "1.0.0",
	"Updated": "2024-04-21T00:54:23+00:00",
	"Downloads": [
		{
			"Id": 94063,
			"Type": "Main",
			"DisplayName": "Beachside Livestock",
			"FileName": "Beachside Livestock-22930-1-0-0-1713660863.zip",
			"Description": "",
			"Version": "1.0.0",
			"SizeInBytes": 73116,
			"Uploaded": "2024-04-21T00:54:23+00:00",
			"Mods": [
				{
					"Id": null,
					"DisplayName": "Beachside Livestock",
					"Type": "Xnb",
					"RelativePath": "Beachside Livestock",
					"ManifestParseError": "XnbMod",
					"ManifestParseErrorText": "it's not a SMAPI mod (see https://smapi.io/xnb for info)."
				}
			],
			"OtherFields": {
				"Uid": 5596342480751,
				"CategoryId": 1,
				"Primary": false
			}
		}
	],
	"OtherFields": {
		"Uid": 5596342409618,
		"UploaderId": 208185981,
		"CategoryId": 7,
		"Adult": false
	}
}

=== Pathoschild/StardewModDataset/dataset/data/Nexus/22/22097.json
{
	"Site": "Nexus",
	"Id": 22097,
	"Name": "Peachy Objects 1.6 items variation",
	"Author": "Lun1e",
	"AuthorLabel": "Lunie",
	"Description": "[color=#ea9999][b][u]UPDATE![/u][/b][/color]\n<br />\n<br />[size=3][url=https://www.nexusmods.com/stardewvalley/mods/4908]Peachy Objects[/url]\u00A0has now been officially updated! I’m leaving this up for people who want slightly different colours than the official version, but please feel free to remove this mod from your mod list and just get the latest version of Peachy Objects from\u00A0[url=https://www.nexusmods.com/stardewvalley/users/42583370]Peachitto[/url]\uFEFF! ♥️ \n<br />I won't make any more changes to this mod as it's fulfilled its purpose and is no longer needed.[/size]\n<br />\n<br />This is a very basic mod that applies colours changes to Peachy Objects\u00A0icons for jelly, pickles, wine, and juice to make use of 1.6's new colours inclusion.\n<br />All credit to\u00A0[url=https://www.nexusmods.com/stardewvalley/users/42583370]Peachitto[/url]\uFEFF's original mod [url=https://www.nexusmods.com/stardewvalley/mods/4908]Peachy Objects[/url] and [url=https://www.nexusmods.com/stardewvalley/users/8170278]Cheerybelle[/url] for\u00A0\uFEFF[url=https://www.nexusmods.com/stardewvalley/mods/20755]SCAGI[/url]\uFEFF which is what I used as a base for this one.",
	"PageUrl": "https://www.nexusmods.com/stardewvalley/mods/22097",
	"Version": "1.0.1",
	"Updated": "2024-04-08T19:48:51+00:00",
	"Downloads": [
		{
			"Id": 90473,
			"Type": "Main",
			"DisplayName": "Peachy Objects 1.6",
			"FileName": "Peachy Objects 1.6-22097-1-0-1-1712605731.zip",
			"Description": "Main file, requires Content Patcher.",
			"Version": "1.0.1",
			"SizeInBytes": 7522,
			"Uploaded": "2024-04-08T19:48:51+00:00",
			"Mods": [
				{
					"Id": "Lunie.PeachyObjectsfix",
					"DisplayName": "Peachy Objects 1.6 fix",
					"Type": "ContentPack",
					"RelativePath": "[CP] Peachy Objects 1.6 fix",
					"Manifest": {
						"Name": "Peachy Objects 1.6 fix",
						"Description": "This fixes the icons for jelly, pickles, wine, juice, and honey to match Peachy Objects with 1.6's new colour mode.",
						"Author": "Lunie",
						"Version": "1.0.1",
						"MinimumApiVersion": "2.2.0",
						"ContentPackFor": {
							"UniqueId": "Pathoschild.ContentPatcher",
							"MinimumVersion": "1.3.0"
						},
						"Dependencies": [],
						"UpdateKeys": [
							"Nexus:22097"
						],
						"UniqueId": "Lunie.PeachyObjectsfix"
					}
				}
			],
			"OtherFields": {
				"Uid": 5596342477161,
				"CategoryId": 1,
				"Primary": false
			}
		}
	],
	"OtherFields": {
		"Uid": 5596342408785,
		"UploaderId": 187810446,
		"CategoryId": 15,
		"Adult": false
	}
}

=== Pathoschild/StardewModDataset/dataset/data/CurseForge/155/1554084.json
{
	"Site": "CurseForge",
	"Id": 1554084,
	"Name": "JP's PaiNT Anime Girls Portraits 2",
	"Author": "Juanpa98ar",
	"PageUrl": "https://www.curseforge.com/stardewvalley/mods/jps-paint-anime-girls-portraits-2",
	"Version": null,
	"Updated": "2026-05-26T11:12:13.013+00:00",
	"Downloads": [
		{
			"Id": 8146503,
			"Type": "Main",
			"DisplayName": "[CP] PaiNT Anime Portraits 2.zip",
			"FileName": "[CP] PaiNT Anime Portraits 2.zip",
			"Version": null,
			"SizeInBytes": 51129654,
			"Uploaded": "2026-05-26T01:09:54.643+00:00",
			"Mods": [
				{
					"Id": "Juanpa98ar.PAP2",
					"DisplayName": "(JP98) PaiNT Anime Portraits 2",
					"Type": "ContentPack",
					"RelativePath": "[CP] PaiNT Anime Portraits 2",
					"Manifest": {
						"Name": "(JP98) PaiNT Anime Portraits 2",
						"Description": "Anime HD Portraits",
						"Author": "Juanpa98ar",
						"Version": "1.0.0",
						"ContentPackFor": {
							"UniqueId": "Pathoschild.ContentPatcher"
						},
						"Dependencies": [
							{
								"UniqueId": "Juanpa98ar.Code.ShinHDPortraits",
								"IsRequired": true
							}
						],
						"UpdateKeys": [
							"Nexus:46709"
						],
						"UniqueId": "Juanpa98ar.PAP2"
					}
				}
			],
			"OtherFields": {
				"ReleaseType": 1,
				"FileGroupType": 0,
				"gameVersions": [
					"1.6"
				]
			}
		}
	],
	"OtherFields": {
		"Authors": [
			{
				"Id": 139070942,
				"Name": "Juanpa98ar"
			}
		],
		"DateCreated": "2026-05-26T11:02:27.393+00:00",
		"DateReleased": "2026-05-26T01:09:54.643+00:00",
		"DateModified": "2026-05-26T11:12:13.013+00:00",
		"slug": "jps-paint-anime-girls-portraits-2"
	}
}

=== Pathoschild/StardewModDataset/dataset/data/Nexus/32/32448.json
{
	"Site": "Nexus",
	"Id": 32448,
	"Name": "Alpacas (KOR)",
	"Author": "JA3B2",
	"Description": "원본 모드 : [url=http://https://www.nexusmods.com/stardewvalley/mods/8515?tab=files]Alpacas[/url]\n<br />원 모드 제작자 :\u00A0[url=http://https://next.nexusmods.com/profile/omena007]omena007[/url]\n<br />한글 패치 제작자 : JA3B2 (온제비) / 디스코드 : ja3b2\n<br />\n<br />\n<br />Alpacas 모드의 한글 패치 파일입니다.\n<br />원본 다운로드 후 한글 패치를 다운로드 받아 원본 모드 i18n 폴더에 넣어주세요.\n<br />\n<br />\n<br />오탈자, 오역, 기타 오류에 관한 문의는 디스코드 혹은 카페 혹은 넥서스 모드로 보내주시면 감사하겠습니다.\n<br />\n<br />\n<br />[url=https://www.nexusmods.com/stardewvalley/users/78732158]Schamarchs[/url]님의\u00A0[url=http://https://www.nexusmods.com/stardewvalley/mods/29582?tab=files]Moe Alpacas[/url] 모드를 활용해 알파카의 색상을 더욱 다양하게 만들 수 있습니다.",
	"PageUrl": "https://www.nexusmods.com/stardewvalley/mods/32448",
	"Version": "2.2",
	"Updated": "2025-03-17T05:22:33+00:00",
	"Downloads": [
		{
			"Id": 127646,
			"Type": "Main",
			"DisplayName": "Alpacas (KOR)",
			"FileName": "Alpacas (KOR)-32448-2-2-1742188953.zip",
			"Description": "ZIP 파일 압축을 푼 후 '원본 모드 폴더' 중 i18n 폴더에 넣으면 됩니다.",
			"Version": "2.2",
			"SizeInBytes": 431,
			"Uploaded": "2025-03-17T05:22:33+00:00",
			"Mods": [
				{
					"Id": null,
					"DisplayName": "127646",
					"Type": "Invalid",
					"ManifestParseError": "ManifestMissing",
					"ManifestParseErrorText": "it contains files, but none of them are manifest.json."
				}
			],
			"OtherFields": {
				"Uid": 5596342514334,
				"CategoryId": 1,
				"Primary": false
			}
		}
	],
	"OtherFields": {
		"Uid": 5596342419136,
		"UploaderId": 216711583,
		"CategoryId": 7,
		"Adult": false
	}
}

=== Pathoschild/StardewModDataset/dataset/data/Nexus/34/34352.json
{
	"Site": "Nexus",
	"Id": 34352,
	"Name": "Fall Paintings",
	"Author": "Zexu2K",
	"Description": "[size=5][size=5][center][b]Add\u00A0[/b]a few [b]new\u00A0[/b][color=#e69138][b]fall-themed\u00A0[/b][/color][b]paintings\u00A0[/b]to the game![/center][/size][img]https://i.postimg.cc/wTsFm6Rh/banner80.png[/img]\uFEFF\n<br />(Almost every painting has\u00A0a unique colored frame, replacing the standard orange one, with both versions available in the catalog!)\n<br />\n<br />[/size][center][size=5][b]N[/b][b]ew catalog[/b]\u00A0[img]https://i.postimg.cc/J7SvgYb5/cat.png[/img]\u00A0buyable\u00A0in\u00A0[color=#e69138][b]carpenter[/b]\u00A0[/color]shop!\u00A0\uFEFF[/size][/center][size=5][size=6]\n<br />[/size]\n<br />[center][size=5]Check out other mods from the seasons series\uFEFF:\n<br />[/size]*[url=https://www.nexusmods.com/stardewvalley/mods/29965]Winter Paintings[/url]\uFEFF[url=https://www.nexusmods.com/stardewvalley/mods/30126][size=5]\n<br />[color=#ffffff]*[/color]Spring Paintings\n<br />[/size][/url]\uFEFF[/center][/size][size=4]For\u00A0[b]android\u00A0[/b]players use\u00A0[url=https://www.nexusmods.com/stardewvalley/mods/34457]this[/url]\uFEFF, Allows you to access all my catalogues while playing on pc or android, make sure you download the correct version for your device.[/size]",
	"PageUrl": "https://www.nexusmods.com/stardewvalley/mods/34352",
	"Version": "1.1",
	"Updated": "2025-06-15T10:25:39+00:00",
	"Downloads": [
		{
			"Id": 134727,
			"Type": "Main",
			"DisplayName": "Fall Paintings",
			"FileName": "Fall Paintings-34352-1-1-1749983139.zip",
			"Description": "Fixes",
			"Version": "1.1",
			"SizeInBytes": 123454,
			"Uploaded": "2025-06-15T10:25:39+00:00",
			"Mods": [
				{
					"Id": "Zexu2K.Fall_Paintings_by_Zexu2K_CP",
					"DisplayName": "Fall Paintings",
					"Type": "ContentPack",
					"RelativePath": "Fall Paintings\\[CP] Fall Paintings",
					"Manifest": {
						"Name": "Fall Paintings",
						"Description": "Adds Fall Paintings to the game",
						"Author": "Zexu2K",
						"Version": "1.1.0",
						"ContentPackFor": {
							"UniqueId": "Pathoschild.ContentPatcher"
						},
						"Dependencies": [],
						"UpdateKeys": [
							"Nexus:34352"
						],
						"UniqueId": "Zexu2K.Fall_Paintings_by_Zexu2K_CP"
					}
				},
				{
					"Id": "Zexu2K.Fall_Paintings_by_Zexu2K_C",
					"DisplayName": "Fall Paintings",
					"Type": "Smapi",
					"RelativePath": "Fall Paintings\\[C] Fall Paintings",
					"Manifest": {
						"Name": "Fall Paintings",
						"Description": "Adds Catalog for Fall Paintings",
						"Author": "Zexu2K",
						"Version": "1.1.0",
						"MinimumApiVersion": "3.0.0",
						"EntryDll": "Fall Paintings.dll",
						"Dependencies": [
							{
								"UniqueId": "Zexu2K.Fall_Paintings_by_Zexu2K_CP",
								"IsRequired": true
							}
						],
						"UpdateKeys": [
							"Nexus:34352"
						],
						"UniqueId": "Zexu2K.Fall_Paintings_by_Zexu2K_C"
					}
				}
			],
			"OtherFields": {
				"Uid": 5596342521415,
				"CategoryId": 1,
				"Primary": false
			}
		}
	],
	"OtherFields": {
		"Uid": 5596342421040,
		"UploaderId": 55430287,
		"CategoryId": 23,
		"Adult": false
	}
}
