=== Pathoschild/StardewModDataset/dataset/data/json-schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Mod page metadata",
	"description": "The metadata for a Stardew Valley mod page fetched from CurseForge, ModDrop, or Nexus Mods.",
	"type": "object",
	"properties": {
		"Site": {
			"description": "The mod site which has the mod.",
			"type": "string",
			"enum": [ "CurseForge", "ModDrop", "Nexus" ]
		},
		"Id": {
			"description": "The mod page ID within the mod site.",
			"type": "integer"
		},
		"Name": {
			"description": "The mod name based on the mod page.",
			"type": [ "string", "null" ]
		},
		"Author": {
			"description": "The author's canonical name based on the mod page (usually the username). This is identical for all mods uploaded to the same site by a user.",
			"type": [ "string", "null" ]
		},
		"AuthorLabel": {
			"description": "The author's display name based on the mod page, if different from Author. This may differ across mods by the same author, may include free text entered by the uploader on Nexus, or may include multiple names on CurseForge.",
			"type": [ "string", "null" ]
		},
		"TagLine": {
			"description": "A short blurb which describes the mod page, if available.",
			"type": [ "string", "null" ]
		},
		"Description": {
			"description": "The full mod page description body, if available. The format depends on the mod site (e.g. ModDrop uses Markdown and Nexus uses BBCode).",
			"type": [ "string", "null" ]
		},
		"PageUrl": {
			"description": "The full URL to the mod's web page.",
			"type": "string",
			"format": "uri"
		},
		"Version": {
			"description": "The version number based on the mod page, if available. This is the version as shown on the mod page, which may not be a valid semantic version.",
			"type": [ "string", "null" ]
		},
		"Updated": {
			"description": "When the mod metadata last changed, as an ISO 8601 UTC date/time. To the extent supported by each mod site, this covers any change to the mod page (including mod page edits, file uploads, hiding or republishing, etc).",
			"type": "string",
			"format": "date-time"
		},
		"Downloads": {
			"description": "The active downloads on the mod page. The selected files depend on the mod site: CurseForge includes all files; ModDrop includes all files not marked 'old', 'hidden', or 'deleted'; and Nexus includes all files not marked 'old', 'archived', or 'deleted'.",
			"type": "array",
			"items": {
				"$ref": "#/$defs/ModPageDownload"
			}
		},
		"OtherFields": {
			"description": "The remaining fields which weren't mapped to one of the other fields.",
			"type": "object"
		}
	},
	"required": [ "Site", "Id", "Name", "Author", "PageUrl", "Version", "Updated", "Downloads" ],

	"$defs": {
		"ModPageDownload": {
			"description": "A download entry on a mod page.",
			"type": "object",
			"properties": {
				"Id": {
					"description": "The unique ID for this file within the mod site.",
					"type": "integer"
				},
				"Type": {
					"description": "The download type. The meaning depends on the mod site: on CurseForge, 'release' downloads are Main and 'alpha' or 'beta' downloads are Optional; on ModDrop, non-prerelease and non-alternate downloads are Main; on Nexus, files in the 'main' category are Main and those in the 'optional' category are Optional. (For Nexus, all downloads are Optional if the mod page only contains files in non-archived/old/deleted categories that would normally be excluded.)",
					"type": "string",
					"enum": [ "Main", "Optional" ]
				},
				"DisplayName": {
					"description": "The download's title as entered by the uploader.",
					"type": [ "string", "null" ]
				},
				"FileName": {
					"description": "The name of the file when downloaded (usually a .zip file).",
					"type": [ "string", "null" ]
				},
				"Description": {
					"description": "The description text for the file. This may be BBCode on Nexus.",
					"type": [ "string", "null" ]
				},
				"Version": {
					"description": "The version number based on the download info, if any. This is the version as shown on the mod page, which may not be a valid semantic version.",
					"type": [ "string", "null" ]
				},
				"SizeInBytes": {
					"description": "The size of the downloaded file in bytes.",
					"type": "integer",
					"minimum": 0
				},
				"Uploaded": {
					"description": "When the file was uploaded, as an ISO 8601 UTC date/time.",
					"type": "string",
					"format": "date-time"
				},
				"Mods": {
					"description": "The mods detected within this download, based on analysis using the SMAPI toolkit. This is always non-empty, unless the DownloadError or UnpackError fields are set.",
					"type": "array",
					"items": {
						"$ref": "#/$defs/ModFolder"
					}
				},
				"DownloadError": {
					"description": "An error message indicating why the file could not be downloaded, if applicable. This is usually an issue on the mod site (e.g. they quarantined the file).",
					"type": "string"
				},
				"UnpackError": {
					"description": "An error message indicating why the mods could not be unpacked from the downloaded archive, if applicable. This is usually an issue with the file itself (e.g. the author uploaded a corrupted archive).",
					"type": "string"
				},
				"OtherFields": {
					"description": "The remaining fields which weren't mapped to one of the other fields.",
					"type": "object"
				}
			},
			"required": [ "Id", "Type", "DisplayName", "FileName", "Version", "SizeInBytes", "Uploaded", "Mods" ]
		},

		"ModFolder": {
			"description": "A mod folder detected within a download.",
			"type": "object",
			"properties": {
				"Id": {
					"description": "The normalized mod ID from the mod's manifest.json, if found.",
					"type": [ "string", "null" ]
				},
				"DisplayName": {
					"description": "The display name for the mod. This is usually the normalized name from the manifest.json (if it was parseable), else generated based on the folder path in the download.",
					"type": "string"
				},
				"Type": {
					"description": "The detected mod type. One of: ContentPack (contains files loaded as a content pack by another SMAPI mod); Smapi (uses SMAPI directly, e.g. a C# mod); Xnb (a legacy type which replaces game files directly); Ignored (folder is ignored by convention, e.g. because it's prefixed with a dot); or Invalid (mod is invalid and its type could not be determined).",
					"type": "string",
					"enum": [ "ContentPack", "Ignored", "Invalid", "Smapi", "Xnb" ]
				},
				"RelativePath": {
					"description": "The relative path to this mod within the download. Omitted if the mod occupies the entire download.",
					"type": "string"
				},
				"Manifest": {
					"description": "The mod's parsed manifest.json file, if it could be parsed. This is the normalized JSON structure, not the raw text (e.g. JSON comments aren't included).",
					"$ref": "#/$defs/ModManifest"
				},
				"ManifestParseError": {
					"description": "If the mod's manifest.json couldn't be parsed, the error type. One of: EmptyFolder (folder is empty or contains only ignored files); EmptyVortexFolder (folder is an empty folder managed by the Vortex mod manager); IgnoredFolder (folder is ignored by convention); ManifestInvalid (mod's manifest.json could not be parsed); ManifestMissing (folder contains non-ignored and non-XNB files, but none of them are manifest.json); or XnbMod (folder is an XNB mod).",
					"type": "string",
					"enum": [ "EmptyFolder", "EmptyVortexFolder", "IgnoredFolder", "ManifestInvalid", "ManifestMissing", "XnbMod" ]
				},
				"ManifestParseErrorText": {
					"description": "If the mod's manifest.json couldn't be parsed, a human-readable message indicating why (e.g. the message shown in the SMAPI console window).",
					"type": "string"
				}
			},
			"required": [ "Id", "DisplayName", "Type" ]
		},

		"ModManifest": {
			"description": "The parsed manifest.json for a scanned mod.",
			"type": "object",
			"properties": {
				"Name": {
					"description": "The mod name.",
					"type": [ "string", "null" ]
				},
				"Description": {
					"description": "A brief description of the mod.",
					"type": [ "string", "null" ]
				},
				"Author": {
					"description": "The mod author's name.",
					"type": [ "string", "null" ]
				},
				"Version": {
					"description": "The mod version. This is guaranteed to be a semantic version (since an invalid version results in a manifest parse error).",
					"type": "string"
				},
				"MinimumApiVersion": {
					"description": "The minimum SMAPI version required by this mod, if specified. This is guaranteed to be a semantic version.",
					"type": "string"
				},
				"MinimumGameVersion": {
					"description": "The minimum Stardew Valley version required by this mod, if specified. This is guaranteed to be a semantic version.",
					"type": "string"
				},
				"EntryDll": {
					"description": "The name of the DLL to load in the mod directory, if it's a SMAPI (C#) mod.",
					"type": "string"
				},
				"ContentPackFor": {
					"description": "The mod which will read this as a content pack, if it's a content pack.",
					"$ref": "#/$defs/ModManifestContentFor"
				},
				"Dependencies": {
					"description": "The other mods that must be loaded before this mod.",
					"type": "array",
					"items": {
						"$ref": "#/$defs/ModManifestDependency"
					}
				},
				"UpdateKeys": {
					"description": "The namespaced mod IDs to query for updates (like \"Nexus:541\").",
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"UniqueId": {
					"description": "The unique mod ID.",
					"type": "string"
				},
				"OtherFields": {
					"description": "The remaining fields which weren't mapped to one of the other fields.",
					"type": "object"
				}
			},
			"required": [ "Name", "Description", "Author", "Version", "UpdateKeys", "UniqueId" ]
		},

		"ModManifestContentFor": {
			"description": "The mod that will load a content pack, from the content pack's manifest.",
			"type": "object",
			"properties": {
				"UniqueId": {
					"description": "The unique ID of the mod which can read this content pack.",
					"type": [ "string", "null" ]
				},
				"MinimumVersion": {
					"description": "The minimum required version (if any).",
					"type": [ "string", "null" ]
				}
			},
			"required": [ "UniqueId" ]
		},

		"ModManifestDependency": {
			"description": "A mod dependency listed in a mod manifest.",
			"type": "object",
			"properties": {
				"UniqueId": {
					"description": "The unique mod ID to require.",
					"type": [ "string", "null" ]
				},
				"MinimumVersion": {
					"description": "The minimum required version (if any).",
					"type": "string"
				},
				"IsRequired": {
					"description": "Whether the dependency must be installed to use the mod.",
					"type": "boolean"
				}
			},
			"required": [ "UniqueId", "IsRequired" ]
		}
	}
}

=== Pathoschild/StardewModDataset/dataset/data/Nexus/42/42400.json
{
	"Site": "Nexus",
	"Id": 42400,
	"Name": "Grandpa's Toolbelt (PTBR)",
	"Author": "Maatsuki",
	"Description": "[left][/left]\n<br />[img]https://i.postimg.cc/wMFMHCkY/sobre_o_mod2.png[/img]\n<br />[center][b][size=5]\n<br />Você herdou o bem mais precioso do Vovô: seu fiel cinto de ferramentas!\n<br />Esse mod adiciona seis espaços permanentes, separados da sua mochila, para economizar espaço e garantir que você nunca fique na mão sem seus itens mais usados[b]\u00A0[/b]✨[/size][/b][/center]\n<br />\n<br />[center][b][size=5]PÁGINA DO MOD [size=5]✨[/size]\n<br />[/size][size=5][url=https://www.nexusmods.com/stardewvalley/mods/42217][b]Grandpa's Toolbelt\n<br />[/b][/url]\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF[/size]\n<br />\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF\uFEFF[img]https://i.postimg.cc/4ywyZD1G/Info2.png[/img]\n<br />\n<br />\uFEFF[/b][size=5][b]O Mais Lore-Friendly que eu consegui [size=5]✨[/size][/b]\n<br />[b]Revisado novamente antes de ser postado aqui, qualquer errinho será corrigido no futuro [size=5]✨[/size][/b][/size]\n<br /> \n<br />[img]https://i.postimg.cc/QCSCs2qG/Creditos2.png[/img]\uFEFF\n<br /> \n<br />[b][size=5]Criador do Mod Original [size=5]✨[/size][/size][/b]\n<br />[size=5][b][url=https://www.nexusmods.com/stardewvalley/users/19851364]ThatBritishMo[/url]\u00A0|\u00A0imnotashrimp83\n<br />[/b][/size]\n<br />[b][size=5]Criador da Tradução [size=5]✨[/size][/size][/b]\n<br />[size=5][url=https://www.nexusmods.com/users/59340891][b]Maatsuki[/b][/url][/size]\n<br /> \uFEFF [/center]\n<br />\uFEFF\uFEFF[url=https://discord.gg/yfz6pZZ6X6][img]https://i.imgur.com/OMFnY4K.png[/img][/url]\uFEFF\uFEFF\n<br />[center]Visite nosso Discord clicando[url=https://discord.gg/yfz6pZZ6X6] NESTE LINK![/url]\uFEFF Junte-se à melhor comunidade entusiasta de mods de Stardew Valley no Brasil![size=4]\n<br />\u00A0Se você é um tradutor, esteja mais do que convidado a se juntar à nós, será um prazer recebe-lo![/size][/center]\n<br />",
	"PageUrl": "https://www.nexusmods.com/stardewvalley/mods/42400",
	"Version": "2.1.6",
	"Updated": "2026-03-31T22:24:50+00:00",
	"Downloads": [
		{
			"Id": 162978,
			"Type": "Main",
			"DisplayName": "Grandpa's Toolbelt (PTBR)",
			"FileName": "Grandpa's Toolbelt (PTBR)-42400-2-1-6-1774995890.zip",
			"Description": "",
			"Version": "2.1.6",
			"SizeInBytes": 905,
			"Uploaded": "2026-03-31T22:24:50+00:00",
			"Mods": [
				{
					"Id": null,
					"DisplayName": "GrandpasToolbelt\\i18n",
					"Type": "Invalid",
					"RelativePath": "GrandpasToolbelt\\i18n",
					"ManifestParseError": "ManifestMissing",
					"ManifestParseErrorText": "it contains files, but none of them are manifest.json."
				}
			],
			"OtherFields": {
				"Uid": 5596342549666,
				"CategoryId": 1,
				"Primary": true
			}
		}
	],
	"OtherFields": {
		"Uid": 5596342429088,
		"UploaderId": 59340891,
		"CategoryId": 27,
		"Adult": false
	}
}

=== Pathoschild/StardewModDataset/dataset/data/Nexus/11/11341.json
{
	"Site": "Nexus",
	"Id": 11341,
	"Name": "Happy Birthday PT BR",
	"Author": "Kiyugamods",
	"AuthorLabel": "Kiyuga",
	"Description": "[center][/center]\n<br />[center][font=Comic Sans MS][b][color=#ffe599][size=6]Tradução Completa![/size][/color]\n<br />\n<br />[/b][size=2]Na versão\u00A03.21.4 - Para\u00A0Happy Birthday ([color=#00ff00]Requer[/color])\n<br />Na versão\u00A02.0.4 - Para\u00A0Happy Birthday English Content Pack ([color=#ff0000]Não Requer[/color])[/size]\n<br />\n<br />\n<br />[color=#b6d7a8][size=6][b][img]https://i.imgur.com/S0n9jix.png[/img][/b][/size][/color]\n<br />\n<br />\n<br />[size=4]Você já se perguntou por que você não faz aniversário em Stardew Valley? Bem, não se preocupe mais!\n<br />Este mod permite que você escolha um dia para o seu aniversário. No seu aniversário, você recebera cartas de seus pais, e os aldeões lhe dão presentes e lhe desejaram um feliz aniversário.[/size][/font]\n<br />[font=Comic Sans MS]\n<br />\n<br />[color=#6fa8dc][size=6][b][img]https://i.imgur.com/fuPIcwr.png[/img][/b][/size][/color]\n<br />\n<br />\n<br />[size=5][b]Criador do mod:\u00A0[url=https://www.nexusmods.com/stardewvalley/users/111142118][/url][url=https://www.nexusmods.com/stardewvalley/users/32171640]Ômegase[/url][/b][/size][b][size=5]\uFEFF\uFEFF[url=https://www.nexusmods.com/stardewvalley/users/111722573][/url][url=https://www.nexusmods.com/stardewvalley/users/111142118][/url]\n<br />Tradução:\u00A0Kiyugamods\n<br />\n<br />[color=#ffd966][size=3]Proibido\u00A0Reposta/Copiar/Atualizar \"Minhas\" Traduções sem a minha autorização.\n<br />Sujeito a Denuncia/Report por roubo de propriedade.[/size][/color][/size]\n<br />\n<br />\n<br />[img]https://i.imgur.com/UCaKj8m.png[/img]\n<br />\n<br />[/b]Siga Exatamente na nessa ordem\n<br />(Eu vou pular o básico como SMAPI e Content)\n<br />\n<br />1° Primeiramente\n<br />Baixe o mod Original\n<br />[url=https://www.nexusmods.com/stardewvalley/mods/520]Happy Birthday[/url]\uFEFF\n<br />\n<br />2° Segundo\n<br />Baixe os requisitos\n<br />- [url=https://www.nexusmods.com/stardewvalley/mods/1348]SpaceCore[/url]\uFEFF\n<br />\u00A0-\u00A0[url=https://www.nexusmods.com/stardewvalley/mods/2341]Stardust Core\n<br />\n<br />[/url][color=#ff0000][b]NÃO INSTALE O REQUSITO[/b][/color][/font]\n<br />[font=Comic Sans MS][url=https://www.nexusmods.com/stardewvalley/mods/11148]Happy Birthday English Content Pack\uFEFF\n<br />[/url]\n<br />3° Terceiro\n<br />Baixe a minha a Tradução\n<br />[url=https://www.nexusmods.com/stardewvalley/mods/11341?tab=files]\u00A0Happy Birthday Portugues Content Pack[/url]\uFEFF\n<br />\n<br />4° Quarto\n<br />Coleque o original\u00A0[url=https://www.nexusmods.com/stardewvalley/mods/520]Happy Birthday[/url]\u00A0e requisitos na pasta de /Mods\n<br />Em seguida coloque também a Tradução\u00A0[url=https://www.nexusmods.com/stardewvalley/mods/11341?tab=files]\u00A0Happy Birthday Portugues Content Pack[/url]\u00A0na mesma pasta.\n<br />\n<br />\n<br />Obs: Não precisa substituir nenhum arquivo.\n<br />[b]NÃO\u00A0[/b]precisa e não deve ter\u00A0[url=https://www.nexusmods.com/stardewvalley/mods/11148]English Content Pack[/url]\n<br />\n<br />Tudo certo para funcionar corretamente.[/font]\n<br />\n<br />\n<br />[/center]\n<br />[center][/center]\n<br />[center][b][size=5]===================[/size]\n<br />[size=5]Parceiros no Discord![/size]\n<br />[size=4](Clique na Imagem Para fazer Parte)[/size]\n<br />[size=5]================[/size]\n<br />\n<br />[/b][url=https://discord.gg/yfz6pZZ6X6][b][img]https://i.imgur.com/OMFnY4K.png[/img][/b]\n<br />[/url][/center]\n<br />",
	"PageUrl": "https://www.nexusmods.com/stardewvalley/mods/11341",
	"Version": "3.21.4",
	"Updated": "2026-09-03T01:53:22+00:00",
	"Downloads": [
		{
			"Id": 181243,
			"Type": "Main",
			"DisplayName": "Happy Birthday Portugues Content Pack",
			"FileName": "e6/e9/1b/e6e91b84-ba12-42cd-9941-4ca27c8548f9",
			"Description": "Baixe apenas o Mod Happy Birthday (3.21.4 Versão Mais Atualizada)\n\n- Extraia a tradução na pasta (Stardew Valley/Mods)\nObs: Não precisa ser dentro da pasta do (Mod Happy Birthday).\n\n(Não instale English Content Pack - Esse mod aqui faz o trabalho dele)",
			"Version": "3.21.4",
			"SizeInBytes": 51878,
			"Uploaded": "2026-09-03T01:53:22+00:00",
			"Mods": [
				{
					"Id": "Omegasis.HappyBirthday.ContentPatcher.ContentPack.pt-BR",
					"DisplayName": "Happy Birthday en-US Translation Content Pack",
					"Type": "ContentPack",
					"RelativePath": "[CP] HappyBirthdayContentPack pt-BR",
					"Manifest": {
						"Name": "Happy Birthday en-US Translation Content Pack",
						"Description": "Traduções em português para o mod, Happy Birthday.",
						"Author": "Omegasis",
						"Version": "3.21.4",
						"ContentPackFor": {
							"UniqueId": "Pathoschild.ContentPatcher"
						},
						"Dependencies": [
							{
								"UniqueId": "Omegasis.HappyBirthday",
								"MinimumVersion": "3.21.0",
								"IsRequired": true
							}
						],
						"UpdateKeys": [
							"Nexus:11341"
						],
						"UniqueId": "Omegasis.HappyBirthday.ContentPatcher.ContentPack.pt-BR",
						"OtherFields": {
							"Translator": "Kiyugamods"
						}
					}
				}
			],
			"OtherFields": {
				"Uid": 5596342567931,
				"CategoryId": 1,
				"Primary": true
			}
		}
	],
	"OtherFields": {
		"Uid": 5596342398029,
		"UploaderId": 106092643,
		"CategoryId": 3,
		"Adult": false
	}
}

=== Pathoschild/StardewModDataset/dataset/data/Nexus/27/27978.json
{
	"Site": "Nexus",
	"Id": 27978,
	"Name": "Taelende's Void Ranch for 1.6",
	"Author": "silvermoonchan",
	"AuthorLabel": "Taelende silvermoonchan",
	"Description": "Permissions for Taelende's\u00A0[url=https://www.nexusmods.com/stardewvalley/mods/2696]Void Ranch[/url]\u00A0were open, so I've taken the liberty of updating it to 1.6!\n<br />\n<br />This mod adds {not replaces!) void versions of all the vanilla animals. They include:\n<br />\n<br />Coop:\n<br />4 varieties of Fancy Void Chickens\n<br />A Void Duck\n<br />A Void Rabbit\n<br />A Void Dinosaur\n<br />\n<br />Barn:\n<br />2 varieties of Void Cow\n<br />A Void Sheep\n<br />A Void Goat\n<br />A Void Pig\n<br />\n<br />All these animals can be purchased from Marnie. The cows, goats, chickens and dino produce vanilla milks and eggs, and the pig digs up truffles like vanilla pigs. The duck lays a vanilla egg but drops a void feather. The sheep and rabbits will provide void wool that can be turned into void cloth, and rabbits drop void rabbit's feet with high friendship.\n<br />\n<br />This mod does NOT include the horse from the original since that was a retexture of the vanilla horse and not a barn or coop animal.\n<br />\n<br />Enjoy!\n<br />\n<br />~Like my work? [url=https://ko-fi.com/silvermoonchan]Buy me a coffee![/url] ☕ ",
	"PageUrl": "https://www.nexusmods.com/stardewvalley/mods/27978",
	"Version": "1.7",
	"Updated": "2026-03-27T03:04:31+00:00",
	"Downloads": [
		{
			"Id": 162282,
			"Type": "Main",
			"DisplayName": "Void Ranch",
			"FileName": "Void Ranch-27978-1-7-1774580671.zip",
			"Description": "format update",
			"Version": "1.7",
			"SizeInBytes": 120231,
			"Uploaded": "2026-03-27T03:04:31+00:00",
			"Mods": [
				{
					"Id": "Taelende.VoidRanch",
					"DisplayName": "Void Ranch",
					"Type": "ContentPack",
					"RelativePath": "Void Ranch\\[CP] Void Ranch",
					"Manifest": {
						"Name": "Void Ranch",
						"Description": "Enter the void. Embrace the void.",
						"Author": "Taelende silvermoonchan",
						"Version": "1.7.0",
						"MinimumApiVersion": "2.6.0",
						"ContentPackFor": {
							"UniqueId": "Pathoschild.ContentPatcher"
						},
						"Dependencies": [],
						"UpdateKeys": [
							"Nexus:27978"
						],
						"UniqueId": "Taelende.VoidRanch"
					}
				}
			],
			"OtherFields": {
				"Uid": 5596342548970,
				"CategoryId": 1,
				"Primary": false
			}
		}
	],
	"OtherFields": {
		"Uid": 5596342414666,
		"UploaderId": 10252540,
		"CategoryId": 7,
		"Adult": false
	}
}

=== Pathoschild/StardewModDataset/dataset/data/Nexus/35/35606.json
{
	"Site": "Nexus",
	"Id": 35606,
	"Name": "Lnh's Dreamy Island Farm",
	"Author": "liunianhui",
	"Description": "[center][size=4][color=#ffff00]接受地图绘制委托，如果你正在制作mod，需要找人绘制地图，那么请联系我。\n<br />Accept the commission of map drawing. If you are making mod and need to find someone to draw a map, please contact me.[/color]\n<br />\n<br />[color=#00ff00]这个农场不是很大，但是所有地都可以种植。\n<br />有丰富的鱼群，还有2个自定义地图，可以建造农场建筑。\n<br />左下角每天会刷新7个硬木桩，可以在配置中取消刷新。\n<br />默认替换标准农场\n<br />This farm is not big, but all the land can be planted.\n<br />There are many fish species.\n<br />There are also 2 custom maps available for building farm buildings.\n<br />The bottom left corner refreshes 7 hardwood stakes every day.\u00A0Can be disabled in the config file.\n<br />Default replacement of standard farm[/color]\n<br />[color=#ff0000]\n<br />如果你喜欢它，可以点个赞吗？非常感谢\n<br />If you like it, can you endorse it?\u00A0Thank you!\n<br />\n<br />[/color]这是来自群友好久不见的约稿地图，让我在这里发布\n<br />\n<br />[color=#00ffff]b站：[url=https://space.bilibili.com/378625642?spm_id_from=333.1007.0.0]LiuNianHui_Lnh\n<br />[/url]交流群：714558944\n<br />如果你喜欢我的mod，可以[url=https://afdian.com/a/420817996Lnh]请我喝杯咖啡[/url]\uFEFF吗？\n<br />If you like my mod, can you\u00A0[url=https://ko-fi.com/liunianhui]buy me a cup of coffee[/url]\uFEFF\uFEFF?[/color][/size][/center]",
	"PageUrl": "https://www.nexusmods.com/stardewvalley/mods/35606",
	"Version": "1.0.1",
	"Updated": "2025-08-07T04:32:15+00:00",
	"Downloads": [
		{
			"Id": 139393,
			"Type": "Main",
			"DisplayName": "Lnh's Dreamy Island Farm",
			"FileName": "Lnh's Dreamy Island Farm-35606-1-0-1-1754541135.zip",
			"Description": "更新内容在mod主页变更日志里/The updated content is in the mod homepage change logs",
			"Version": "1.0.1",
			"SizeInBytes": 417163,
			"Uploaded": "2025-08-07T04:32:15+00:00",
			"Mods": [
				{
					"Id": "Lnh.DreamyIslandFarm",
					"DisplayName": "Lnh's Dreamy Island Farm",
					"Type": "ContentPack",
					"RelativePath": "Lnh's Dreamy Island Farm",
					"Manifest": {
						"Name": "Lnh's Dreamy Island Farm",
						"Description": "",
						"Author": "Lnh",
						"Version": "1.0.1",
						"ContentPackFor": {
							"UniqueId": "Pathoschild.ContentPatcher"
						},
						"Dependencies": [],
						"UpdateKeys": [
							"Nexus:35606"
						],
						"UniqueId": "Lnh.DreamyIslandFarm"
					}
				}
			],
			"OtherFields": {
				"Uid": 5596342526081,
				"CategoryId": 1,
				"Primary": false
			}
		}
	],
	"OtherFields": {
		"Uid": 5596342422294,
		"UploaderId": 91684178,
		"CategoryId": 21,
		"Adult": false
	}
}

=== Pathoschild/StardewModDataset/dataset/data/Nexus/27/27303.json
{
	"Site": "Nexus",
	"Id": 27303,
	"Name": "Fence Expanded (Spanish)",
	"Author": "Hayato2236",
	"AuthorLabel": "Zexu2K y Hayato2236",
	"Description": "[center][b]\uFEFF(Las imágenes son solo ilustrativas, en el juego las verán en español)[/b]\n<br />\n<br />Utilice [b]el catálogo de vallas[/b] para obtener [b]nuevas vallas\u00A0[/b]\n<br />\n<br />[b][size=4]¡Que puedes comprar en la carpintería de Robin![/size][/b]\n<br />\n<br />[b]Lista de vallas nuevas:[/b]\n<br />\n<br />[img]https://i.postimg.cc/nzjg1K6H/fenlist.png[/img]\uFEFF\n<br />\n<br />[b]Cómo se ven:[/b]\n<br />\n<br />[img]https://i.postimg.cc/g0B1RttS/fen.png[/img]\uFEFF\n<br />\n<br />[img]https://i.postimg.cc/pTbYgDmV/dsadsadsadsad.png[/img]\uFEFF\n<br />\n<br />[b][size=4]Revisa sus otros mod (de verdad, míralos, están geniales):[/size][/b]\n<br />\n<br />[size=5]-\u00A0[url=https://www.nexusmods.com/stardewvalley/mods/25838]Monster Energy Drink's\n<br />[/url]-\u00A0[url=https://www.nexusmods.com/stardewvalley/mods/25080]Fast Eat\n<br />[/url]-\u00A0[url=https://www.nexusmods.com/stardewvalley/mods/27265]Battery Robot\n<br />[/url]\uFEFF-\u00A0[url=https://www.nexusmods.com/stardewvalley/mods/26887]Repice Researcher\n<br />[/url]\uFEFF- \uFEFF[url=https://www.nexusmods.com/stardewvalley/mods/26498]Ancient Seed Expanded\n<br />\n<br />[/url][/size][b]Instalación de la traducción[/b]\n<br />Descarga, descomprime y copia la carpeta\u00A0[b]Fence Expanded[/b] en [b][i]stardew vallewy/mods[/i][/b], reemplaza si lo solicita\u00A0[/center]",
	"PageUrl": "https://www.nexusmods.com/stardewvalley/mods/27303",
	"Version": "1.4.1",
	"Updated": "2025-05-16T03:11:46+00:00",
	"Downloads": [
		{
			"Id": 132371,
			"Type": "Main",
			"DisplayName": "Fence Expanded Spanish v1.4.1",
			"FileName": "Fence Expanded Spanish v1.4.1-27303-1-4-1-1747365106.zip",
			"Description": "Corregido un error de tipeo",
			"Version": "1.4.1",
			"SizeInBytes": 1667,
			"Uploaded": "2025-05-16T03:11:46+00:00",
			"Mods": [
				{
					"Id": null,
					"DisplayName": "Fence Expanded\\Fence Expanded\\[CP] Fence Expanded\\i18n",
					"Type": "Invalid",
					"RelativePath": "Fence Expanded\\Fence Expanded\\[CP] Fence Expanded\\i18n",
					"ManifestParseError": "ManifestMissing",
					"ManifestParseErrorText": "it contains files, but none of them are manifest.json."
				}
			],
			"OtherFields": {
				"Uid": 5596342519059,
				"CategoryId": 1,
				"Primary": false
			}
		}
	],
	"OtherFields": {
		"Uid": 5596342413991,
		"UploaderId": 180180273,
		"CategoryId": 7,
		"Adult": false
	}
}

=== Pathoschild/StardewModDataset/dataset/data/Nexus/33/33023.json
{
	"Site": "Nexus",
	"Id": 33023,
	"Name": "West Coast North America bird pack PT-BR",
	"Author": "runangiejar",
	"Description": "A [b]Guilda dos Ornitólogos[/b] traz uma experiência totalmente nova de observação de aves para [i]Stardew Valley[/i], completa com mecânicas reformuladas para os pássaros, comedouros e banheiras, aves sazonais, ninhos e filhotes, um sistema de progressão, uma nova localização e loja, um novo NPC com um passado trágico, e muuuito mais! Você tem o que é preciso para se tornar o próximo grande observador de aves de Pelican Town?\n<br />\n<br />[b]Pacotes de Aves[/b] \n<br /> Novo! [b]Aves da Costa Oeste da América do Norte[/b] (Este) \n<br />[b]Aves Eurasianas[/b] por Mazout \n<br /> [b]Aves de Arrbyte[/b] \n<br /> [b]Pacote de Parulídeos do GCWA[/b]",
	"PageUrl": "https://www.nexusmods.com/stardewvalley/mods/33023",
	"Version": "1.0.0",
	"Updated": "2025-04-20T23:24:22+00:00",
	"Downloads": [
		{
			"Id": 130529,
			"Type": "Main",
			"DisplayName": "OG West Coast Birds PT-BR",
			"FileName": "OG West Coast Birds PT-BR-33023-1-0-1-1745191462.zip",
			"Description": "Basta extraí-lo para a pasta mods e substituir os arquivos",
			"Version": "1.0.1",
			"SizeInBytes": 7176,
			"Uploaded": "2025-04-20T23:24:22+00:00",
			"Mods": [
				{
					"Id": null,
					"DisplayName": "[OG] West Coast Birds PT-BR\\[OG] West Coast Birds\\i18n",
					"Type": "Invalid",
					"RelativePath": "[OG] West Coast Birds PT-BR\\[OG] West Coast Birds\\i18n",
					"ManifestParseError": "ManifestMissing",
					"ManifestParseErrorText": "it contains files, but none of them are manifest.json."
				}
			],
			"OtherFields": {
				"Uid": 5596342517217,
				"CategoryId": 1,
				"Primary": false
			}
		}
	],
	"OtherFields": {
		"Uid": 5596342419711,
		"UploaderId": 77711448,
		"CategoryId": 7,
		"Adult": false
	}
}
